### ISSUE TITLE
Remove the Material UI Icons 

### ISSUE THREAD

**Issue by veritem** [kobra-dev/Kobra#124]
Since the beginning of the project, we have been using material UI for all of the components related to the editor,

Material UI is a great library that provides great components and has served us for a really long time and has helped us to be more consistent with our design system, For the sake of the performance of the app, material UI isn't that great.

We need to keep the app as low level as possible to improve the performance and load speed. I think we can try using native CSS instead of a huge library like Material UI which weighs.

- `@material/core` -> [329.1 KB](https://bundlephobia.com/result?p=@material-ui/core@4.11.4)
- `@material/icons` ->  [2.2MB](https://bundlephobia.com/result?p=@material-ui/icons@4.11.2)
- `@material/lab`  -> [71.6KB](https://bundlephobia.com/result?p=@material-ui/lab@4.0.0-alpha.58)

If we can remove material UI from the app we shall save more than `3MB` of the bundle size, I know this is not what we are focused on right now but we should in the next months.

A good alternative that we can use is [tailwindcss](https://tailwindcss.com/) since its just low-level CSS abstracted into utility classes.

To make our design system we can use [storybooks](https://storybook.js.org/) and this should keep us more consistent.

**Comment by pranavnt** [comment]
Renamed it to removing MUI icons as MUI is completely integrated into Kobra

**Comment by Merlin04** [comment]
I think there is a way to import individual icons, we should look into that

**Comment by Merlin04** [comment]
https://mui.com/components/icons/#usage
We can use this method to save bundle size (we also might want to use this for other components, however we use so much of Material UI that it's probably not as necessary)

**Comment by Merlin04** [comment]
It turns out that [MUI does tree shaking automatically](https://mui.com/guides/minimizing-bundle-size/#when-and-how-to-use-tree-shaking), so there isn't any further improvement that we can make.
