### ISSUE TITLE
Writting Tests

### ISSUE THREAD

**Issue by veritem** [kobra-dev/Kobra#125]
To prevent the stuff from being broken unknowingly for sure this project needs tests. like when someone opens a PR we need tests to run checking if there isn't anything broken or if we do any modification we need to be sure we didn't break anything

Talking about tests we can do unit tests and integration tests.

**Comment by halimkerollos** [comment]
Hi, makuzaverite! I love this project and the idea, believe it's the future, and would like to contribute in whatever way I can. I'm relatively inexperienced with programming but am also competent enough to make things happen with some guidance. If you would get back to me with some I can do my best to help with some of these issues and moving the project forward as a whole.

**Comment by pranavnt** [comment]
Hey @halimkerollos! We're so excited that you're interested in contributing, and here's the invite link to our discord server where we can give you guidance: https://discord.gg/58TkKsNXgN. Thanks so much!!
