### ISSUE TITLE
Machine Learning blocks documentation

### ISSUE THREAD

**Issue by Merlin04** [kobra-dev/Kobra#38]
Add documentation:
- explaining what each ML algorithm/model is
- how to use the blocks in general
- any special parameters a model might have (like k value for KNN)

**Comment by halimkerollos** [comment]
I'm willing to help with the documentation and whitepaper, where should I start?

**Comment by Merlin04** [comment]
We should move discussion of this to https://github.com/kobra-dev/docs/issues/7
